FROM openjdk:17-jdk-slim

# Install additional utilities
RUN apt-get update -y && apt-get install -y git unzip

# Create and set the working directory
RUN mkdir -p /app
WORKDIR /app

# Clone the private repository to the container
RUN git clone https://github.com/AnaSofiaFigueiroaPinto/devops-23-24-JPE-PSM-1231822.git

# Set the working directory to the Spring Boot application directory
WORKDIR /app/devops-23-24-JPE-PSM-1231822/CA2/Part2/react-and-spring-data-rest-basic/react-and-spring-data-rest-basic

# Ensure the gradlew script is executable and build the application
RUN chmod +x ./gradlew && ./gradlew clean build

# Configure the container to run as an executable
ENTRYPOINT ["./gradlew"]
CMD ["bootRun"]