# Use Ubuntu as the base image
FROM ubuntu

# Install OpenJDK, unzip, and wget
RUN apt-get update && \
  apt-get install -y openjdk-17-jdk-headless unzip wget

# Create and set the working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Download H2 Database and place it in /opt
RUN wget https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar -O /opt/h2.jar

# Expose the necessary ports
EXPOSE 8082 9092

# Start the H2 Server
CMD ["java", "-cp", "/opt/h2.jar", "org.h2.tools.Server", "-web", "-webAllowOthers", "-tcp", "-tcpAllowOthers", "-ifNotExists"]