pipeline {
    agent any

    stages {
    //What repository to checkout
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AnaSofiaFigueiroaPinto/devops-23-24-JPE-PSM-1231822.git'
                dir('CA2/Part1/gradle_basic_demo') {
                }
            }
        }
        //Redudant stage as tests are already run in the build stage
        stage('Test') {
            steps {
                dir('CA2/Part1/gradle_basic_demo') {
                //Change gradlew permissions
                    sh 'chmod +x gradlew'
                    sh './gradlew test'
                }
            }
        }
        //Create a build stage to compile project
        stage('Build') {
            steps {
                dir('CA2/Part1/gradle_basic_demo') {
                    //Run gradlew clean build task
                    sh './gradlew clean build'
                }
            }
        }
        stage('Archive') {
            steps {
                dir('CA2/Part1/gradle_basic_demo') {
                    archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
                }
            }
        }
    }
}